### ISSUE TITLE
Add support for FormattingOptions in config.toml

### ISSUE THREAD

**Issue by djmoch** [9fans/acme-lsp#72]
Currently, when `acme-lsp` sends a [`Formatting`](https://github.com/9fans/acme-lsp/blob/c376e713db7cc62a78bf3707f2a818e09566fc19/internal/lsp/acmelsp/acmelsp.go#L214) command to the server, it implicitly provides the zero-value for [`FormattingOptions`](https://github.com/9fans/go-lsp-internal/blob/bb36aa85881a7c9174f26fc81782b10591bccfcc/lsp/protocol/tsprotocol.go#L1740), amounting to a `TabSize = 0` and `InsertSpaces = false`.

When using the YAPF plugin with [`python-lsp-server`](https://github.com/python-lsp/python-lsp-server/), these values override the configured behavior. In my case, I'd like to adhere to the [PEP-8](https://peps.python.org/pep-0008/) standard, which would require `TabSize = 4` and `InsertSpaces = true`).

Given all of that, I'd like to propose adding per-server support for `FormattingOptions`. The result would be something like:

``` toml
[Servers]
	[Servers.pylsp]
	Command = ["pylsp", "-vvv"]
	StderrFile = "pylsp.stderr.log"
	LogFile = "pylsp.log"

		# These settings get passed to pylsp
		[Servers.pylsp.Options]
		"pylsp.plugins.autopep8.enabled" = false
		"pylsp.plugins.yapf.enabled" = true

		# These settings get passed on Format
		[Servers.pylsp.FormattingOptions]
		TabSize = 4
		InsertSpaces = true
```

If this seems reasonable, I'd be happy to open a PR to add this.

Please let me know your thoughts.
